import { AboardRelationship } from '../models/aboard.models';

/**
 * Detects whether a relationship describes the *creation* of its target, i.e.
 * the source is a factory that builds/produces the target. Matches on both the
 * machine `type` and the human `label` so authors can phrase it naturally
 * ("Creates", "Generated by", "Produces", "Builds", ...).
 */
const CREATION_PATTERN =
  /creat|generat|produc|build|author|mint|forge|spawn|factor|fabricat|assembl/i;

export function isCreationRelationship(rel: AboardRelationship): boolean {
  return (
    CREATION_PATTERN.test(rel.type ?? '') || CREATION_PATTERN.test(rel.label ?? '')
  );
}
